version: '3'

services:
    app:
        build: .
        command: uvicorn --host 0.0.0.0 --port 80 --reload fescam.router:app
        depends_on: 
            - database
        working_dir: /app/backend
        ports: 
            - 80:80
        volumes: 
            - .:/app
            
    database:
        image: "postgres" # use latest official postgres version
        env_file:
            - ./backend/database.env # configure postgres
        ports: 
            - 5432:5432
        volumes:
            - ./backend/fescam/db/scripts/init-database.sql:/docker-entrypoint-initdb.d/dump.sql
            - database-data:/var/lib/postgresql/data/
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    database-data: