openapi: 3.0.0
info:
  version: '1.0'
  title: PBL
paths:
  /EnfermeiroChefe:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Paciente:
      type: object
      required:
        - CPF
        - Nome
        - Sexo
        - TipoSangue
        - DataDeNasc
        - Endereco
        - Telefone
      properties:
        Nome:
          type: string
        CPF:
          type: string
        Sexo:
          type: string
        TipoSangue:
          type: string
        DataDeNasc:
          type: string
        Endereco:
          type: string
        Telefone:
          type: string
    Estagiario:
      type: object
      required:
        - CPF
        - Nome
        - Tipo
      properties:
        CPF:
          type: string
        Nome:
          type: string
        Tipo:
          type: string
    Administrador:
      type: object
      required:
        - CPF
        - Nome
        - Tipo
      properties:
        CPF:
          type: string
        Nome:
          type: string
        Tipo:
          type: string
    Enfermeiro:
      type: object
      required:
        - CPF
        - Nome
        - Tipo
      properties:
        CPF:
          type: string
        Nome:
          type: string
        Tipo:
          type: string
    EnfermeiroChefe:
      type: object
      required:
        - CPF
        - Nome
        - Tipo
      properties:
        CPF:
          type: string
        Nome:
          type: string
        Tipo:
          type: string
    AgendamentoEnfermeiroChefe:
      type: object
      required:
        - EnfermeiroChefe
        - Enfermeiro
        - Estagiario
        - CPF_Paciente
        - Codigo_Medicamento
      properties:
        EnfermeiroChefe:
          type: string
        Enfermeiro:
          type: string
        Estagiario:
          type: string
        Nome_Paciente:
          type: string
        CPF_Paciente:
          type: string
        Nome_Medicamento:
          type: string
        Codigo_Medicamento:
          type: string
    AlarmeAgendamento:
      type: object
      properties:
        CodigoAlarme:
          type: string
        Nome_Paciente:
          type: string
        Local_Paciente:
          type: string
        Timestamp:
          type: string
        Nome_Medicamento:
          type: string
        Enfermeiro:
          type: string
    Medicamento:
      type: object
      required:
        - Nome
        - Codigo
      properties:  
        Nome:
          type: string
        Codigo:
          type: string
    Prontuario:
      type: object
      required:
        - EnfermeiroChefe
        - Enfermeiro
        - Paciente
        - Dados
        - InternaçãoTimestamp
      properties:
        EnfermeiroChefe:
          type: string
        Paciente:
          type: string
        Dados:
          type: string
        Timestamp:
          type: string
        Enfermeiro:
          type: string
        InternaçãoTimestamp:
          type: string
    CadastroPaciente:
      type: object
      properties:
        EnfermeiroChefe:
          type: string
        Enfermeiro:
          type: string
        Nome_Paciente:
          type: string
        Sexo_Paciente:
          type: string
        DataNascimento:
          type: string
        TipoSangue:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string