default_context:
  project_name: 'FE-S.C.A.M'
  project_slug: 'fe-s.c.a.m'
  domain_main: 'fe-s.c.a.m.com'
  domain_staging: 'stag.fe-s.c.a.m.com'
  docker_swarm_stack_name_main: 'fe-s-c-a-m-com'
  docker_swarm_stack_name_staging: 'stag-fe-s-c-a-m-com'
  secret_key: '123456'
  first_superuser: 'admin@fe-s.c.a.m.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fe-s.c.a.m.com", "https://stag.fe-s.c.a.m.com", "https://fe-s.c.a.m.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fe-s.c.a.m.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@fe-s.c.a.m.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'fe-s.c.a.m.com'
  traefik_constraint_tag_staging: 'stag.fe-s.c.a.m.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
