openapi: 3.0.0
info:
  version: '1.0'
  title: PBL
paths:
  /enfermeirochefe:
    get:
      summary: 'Retorna todos os enfermeiros chefes cadastrado no sistema'
      operationId: getEnfChefe
      tags:
        - enfermeiro_chefe
      responses:
        '200':
          description: 'Retorna a lista de Enfermeiros Chefe'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnfermeiroChefe'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary:

  /enfermeiro_chefe/{enfermeiro_chefe_id}:
    get:
      summary: 'Retorna o enfermeiro chefe com o ID solicitado'
      operationId: getEnfChefeById
      tags:
        - enfermeiro_chefe
      parameters:
        - name: id
          in: query
          description: ID referente ao enfermeiro chefe
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Retorna o enfermeiro chefe do respectivo ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnfermeiroChefe'
        default:
          description: Unexpected error - ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      sumary:
    delete:
      sumary:

  /enfermeiro:
    get:
      summary: 'Retorna todos os enfermeiros cadastrados no sistema'
      operationId: 'getEnfermeiro'
      tags:
        - enfermeiro
      responses:
        '200':
          description: 'Retorna a lista de enfermeiros cadastrados no sistema'
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/EnfermeiroChefe'
        defaut:
          description: Unexpected error
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/Error'
    post:
      summary: 

  /enfermeiro/ {enfermeiro_id}:
    get:
      summary: 'Retorna o enfermeiro referente ao ID solicitado'
      operationId: 'getEnfermeiroById'
      tags:
        - enfermeiro
      parameters:
         - name: id
           in: query
           description: ID referente ao enfermeiro chefe
           required: true
           schema:
             type: integer
             format: int32
      responses:
        '200':
          description: 'Retorna o usuário enfermeiro referente ao ID'
          content: 
          application/json:
            schema:
              $ref: '#/components/schemas/EnfermeiroChefe'
        defaut:
          description: Unexpected error - ID not found
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/Error'
    put:
    delete: 

  /administrador:
    get:
      summary: 'Retorna todos os usuários administradores cadastrado no sistema'
      operationId:  'getAdministrador'
      tags:
        - administrador
      responses:
        '200':
          description: 'Retorna uma lista de todos os administradores do sistema'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Administrador'
        defaut:
          description: Unexpected error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /administrador/ {administrador_id}: 
    get: 
      summary: 'Retorna o usuário administrador referente ao ID solicitado'
      operationId: 'getAdministradorById'
      tags:
        - administrador
      parameters:
        - name: id
          in: query
          description: 'ID referente ao usuario administrador'
          required: true
          schema:
            type: integer
            format: int32
      responses: 
        '200':
          description: 'Retorna o administrador do ID solicitado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Administrador'
        defaut:
          description: Unexpected error - ID not found
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary:
    delete: 
      summary: 

  /agendamento_enfermeiro_chefe: 
    get: 
      summary: 'Retorna uma lista com todos os agendamentos do enfermeiro chefe'
      operationId: getAgendamentoEnfChefe
      tags:
        - agendamentoEnfChefe
      responses: 
        '200':
          description: 'Retorna todos os agendamentos do enfermeiro chefe'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agendamento'
        defaut: 
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary:

  /agendamento_enfermeiro_chefe/{agendamento_enf_chefe_id}: 
    get: 
      summary: 'Retorna o agendamento referente ao ID solicitado'
      operationId: getAgendamentoEnfChefeById
      tags:
        - agendamentoEnfChefe
      parameters:
        - name: id
          in: query
          description: 'ID referente ao agendamento'
          required: true
          schema:
            type: integer
            format: int32
      responses: 
        '200':
          description: 'Retorna o agendamento do ID solicitado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agendamento'
        defaut: 
          description: Unexpected error - ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary:
    delete:
      summary:

  /medicamento:
    get: 
      summary: 'Retorna todos os medicamentos cadastrados no sistema'
      operationId: getMedicamento
      tags:
        - medicamento
      responses:
        '200':
          description: 'Retorna todos os medicamentos cadastrados no sistema'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medicamento'
        defaut:
          description: Unixpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post: 
      summary: 'Cadastra um novo medicamento no sistema'
      operationId: CadastroMedicamento
      tags:
        - medicamento
      parameters:
        - name: Nome
          in: path
          description: 'Nome do medicamento'
          required: true
          schema:
            type: string
        - name: Codigo
          in: path
          description: 'Codigo do medicamento'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Medicamento Salvo com sucesso'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medicamento'
        defaut: 
          description: Unixpected error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /medicamento/{medicamento_id}:
    get:
      summary: 'Retorna um medicamento referente ao ID solicitado'
      operationId: getMedicamentoById
      tags:
        - medicamento
      parameters:
        - name: id
          in: query
          description: 'ID referente ao medicamento'
          required: true
          schema:
            type: integer
            format: int32
      responses: 
        '200':
          description: 'Retorna o medicamento do ID solicitado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medicamento'
        defaut:
          description: Unixpected error - ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary:
    delete:
      summary:
  
    

                
    


components:
  schemas:
    Paciente:
      type: object
      required:
        - CPF
        - Nome
        - DataDeNasc
        - Enfermeiro
      properties:
        Nome:
          type: string
        CPF:
          type: string
        Sexo:
          description: "Sexo biológico"
          type: boolean
          default:
        Genero:
          description: "Gênero com o qual a pessoa se identifica"
          type: string
          enum: ["cis", "trans", "non-b"]
          default: 
        Sangue:
          description: "Tipo sanguíneo"
          type: string
          enum: ["a+", "a-", "b+", "b-", "ab+", "ab-", "o+", "o-", "null_rh"]
          default: 
        DataDeNasc:
          type: string
        Endereco:
          type: string
        Telefone:
          type: string
        CreatedOn:
          type: string
        UpdatedOn:
          type: string
        Enfermeiro:
          description: "O CPF do enfermeiro que cadastrou o paciente"
          type: string
        Dados:
          description: "Informações a respeito do diagnóstico do paciente"
          type: string
    Estagiario:
      type: object
      required:
        - CPF
        - Nome
      properties:
        CPF:
          type: string
        Nome:
          type: string
    Administrador:
      type: object
      required:
        - CPF
        - Nome
      properties:
        CPF:
          type: string
        Nome:
          type: string
    Enfermeiro:
      type: object
      required:
        - CPF
        - Nome
      properties:
        CPF:
          type: string
        Nome:
          type: string
    EnfermeiroChefe:
      type: object
      required:
        - CPF
        - Nome
      properties:
        CPF:
          type: string
        Nome:
          type: string
    Agendamento:
      type: object
      required:
        - Horario
        - EnfermeiroChefe
        - Enfermeiro
        - Estagiario
        - Paciente
        - Medicamento
      properties:
        Horario:
          description: "Timestamp com a hora presvista para execução do agendamento."
          type: string
        EnfermeiroChefe:
          type: string
        Enfermeiro:
          type: string
        Estagiario:
          type: string
        Paciente:
          type: string
        Medicamento:
          type: int
    Medicamento:
      type: object
      required:
        - Nome
        - Codigo
      properties:  
        Nome:
          type: string
        Codigo:
          type: int
    Posologia:
      type: object
      required:
        - Medicamento
        - Paciente
        - Quantidade
      properties:
        id:
          type: int
        Medicamento:
          type: int
        Paciente:
          type: string
        Quantidade:
          description: "A quantidade diária a ser administrada" 
          example: "1 (uma vez ao dia), 0.5 (uma vez a cada dois dias)"
          type: float
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string